/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XarajatlarRouteImport } from './routes/xarajatlar'
import { Route as ShartnomalarRouteImport } from './routes/shartnomalar'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalariesRouteImport } from './routes/salaries'
import { Route as MoliyaRouteImport } from './routes/moliya'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const XarajatlarRoute = XarajatlarRouteImport.update({
  id: '/xarajatlar',
  path: '/xarajatlar',
  getParentRoute: () => rootRouteImport,
} as any)
const ShartnomalarRoute = ShartnomalarRouteImport.update({
  id: '/shartnomalar',
  path: '/shartnomalar',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesRoute = SalariesRouteImport.update({
  id: '/salaries',
  path: '/salaries',
  getParentRoute: () => rootRouteImport,
} as any)
const MoliyaRoute = MoliyaRouteImport.update({
  id: '/moliya',
  path: '/moliya',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/employees': typeof EmployeesRoute
  '/moliya': typeof MoliyaRoute
  '/salaries': typeof SalariesRoute
  '/settings': typeof SettingsRoute
  '/shartnomalar': typeof ShartnomalarRoute
  '/xarajatlar': typeof XarajatlarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/employees': typeof EmployeesRoute
  '/moliya': typeof MoliyaRoute
  '/salaries': typeof SalariesRoute
  '/settings': typeof SettingsRoute
  '/shartnomalar': typeof ShartnomalarRoute
  '/xarajatlar': typeof XarajatlarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/employees': typeof EmployeesRoute
  '/moliya': typeof MoliyaRoute
  '/salaries': typeof SalariesRoute
  '/settings': typeof SettingsRoute
  '/shartnomalar': typeof ShartnomalarRoute
  '/xarajatlar': typeof XarajatlarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/employees'
    | '/moliya'
    | '/salaries'
    | '/settings'
    | '/shartnomalar'
    | '/xarajatlar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/employees'
    | '/moliya'
    | '/salaries'
    | '/settings'
    | '/shartnomalar'
    | '/xarajatlar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/employees'
    | '/moliya'
    | '/salaries'
    | '/settings'
    | '/shartnomalar'
    | '/xarajatlar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  EmployeesRoute: typeof EmployeesRoute
  MoliyaRoute: typeof MoliyaRoute
  SalariesRoute: typeof SalariesRoute
  SettingsRoute: typeof SettingsRoute
  ShartnomalarRoute: typeof ShartnomalarRoute
  XarajatlarRoute: typeof XarajatlarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xarajatlar': {
      id: '/xarajatlar'
      path: '/xarajatlar'
      fullPath: '/xarajatlar'
      preLoaderRoute: typeof XarajatlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shartnomalar': {
      id: '/shartnomalar'
      path: '/shartnomalar'
      fullPath: '/shartnomalar'
      preLoaderRoute: typeof ShartnomalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries': {
      id: '/salaries'
      path: '/salaries'
      fullPath: '/salaries'
      preLoaderRoute: typeof SalariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moliya': {
      id: '/moliya'
      path: '/moliya'
      fullPath: '/moliya'
      preLoaderRoute: typeof MoliyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  EmployeesRoute: EmployeesRoute,
  MoliyaRoute: MoliyaRoute,
  SalariesRoute: SalariesRoute,
  SettingsRoute: SettingsRoute,
  ShartnomalarRoute: ShartnomalarRoute,
  XarajatlarRoute: XarajatlarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
